# Population stability index (PSI)

**Monitor model with Population stability index (PSI)**

+ Because population changes overtime so we need model maintainance i.e: every 6 mths - 1yr or redevelop after getting 50k - 100k new data points. 

+ Index for the different of popoulation overtime (different between trained -past data and new data - current data): PSI - opulation stability Index.

PSI belong to range [0,1. Rebuild model if:
+ 0.1 - 0.25 : little (probably no action needed)
+ 0.25 - 1: big change (action needed)

**Data**

Loan data 2015: download it in the repository

# 1 Data Preparation

import numpy as np
import pandas as pd

from sklearn.linear_model import LogisticRegression
from sklearn import metrics  
from sklearn.metrics import roc_curve, roc_auc_score

import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

#export model
import pickle

# export user-defined functions
%run Userdefined_functions.ipynb

In [2]:
#loading csv files as pd dataframes
loan_data= pd.read_csv ('loan_data_2015.csv',index_col =0, low_memory=False).copy()
inputs_train = pd.read_csv ('loan_data_inputs_train.csv',index_col =0 ).copy()

## Data explore

In [3]:
# Uncomment below to set the pandas dataframe options to display all columns/ rows.
#pd.options.display.max_columns = None
#pd.options.display.max_rows = None

loan_data.shape

(421094, 73)

In [4]:
loan_data.head()

,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,...,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m
id,,,,,,,,,,,,,,,,,,,,,
68444620,73334399,35000,35000,35000.0,60 months,11.99,778.38,C,C1,Foreign Service Officer,...,35367.0,49.3,0.0,1.0,5020.0,40.1,52200.0,1.0,4.0,0.0
68547583,73437441,8650,8650,8650.0,36 months,5.32,260.50,A,A1,Associate Consultant,...,24041.0,88.8,0.0,3.0,3081.0,57.9,26800.0,1.0,0.0,5.0
67849662,72708407,4225,4225,4225.0,36 months,14.85,146.16,C,C5,mechanic,...,3830.0,21.9,0.0,0.0,367.0,22.4,4300.0,0.0,0.0,0.0
68506885,73396712,10000,10000,10000.0,60 months,11.99,222.40,C,C1,CARDIOVASCULAR TECH,...,35354.0,75.5,1.0,1.0,3118.0,67.4,14200.0,1.0,1.0,1.0
68341763,72928789,20000,20000,20000.0,60 months,10.78,432.66,B,B4,truck driver,...,10827.0,72.8,0.0,2.0,2081.0,64.7,14000.0,2.0,5.0,1.0

In [5]:
loan_data.tail()

,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,...,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m
id,,,,,,,,,,,,,,,,,,,,,
36371250,39102635,10000,10000,10000.0,36 months,11.99,332.10,B,B5,Office Assistant,...,NaN,NaN,NaN,NaN,NaN,NaN,17100.0,NaN,NaN,NaN
36441262,39152692,24000,24000,24000.0,36 months,11.99,797.03,B,B5,Director of Maintenance,...,NaN,NaN,NaN,NaN,NaN,NaN,10200.0,NaN,NaN,NaN
36271333,38982739,13000,13000,13000.0,60 months,15.99,316.07,D,D2,Radiologist Technologist,...,NaN,NaN,NaN,NaN,NaN,NaN,18000.0,NaN,NaN,NaN
36490806,39222577,12000,12000,12000.0,60 months,19.99,317.86,E,E3,Painter,...,NaN,NaN,NaN,NaN,NaN,NaN,27000.0,NaN,NaN,NaN
36271262,38982659,20000,20000,20000.0,36 months,11.99,664.20,B,B5,Manager Hotel Operations Oasis,...,NaN,NaN,NaN,NaN,NaN,NaN,41700.0,NaN,NaN,NaN

In [6]:
loan_data.columns.values

array(['member_id', 'loan_amnt', 'funded_amnt', 'funded_amnt_inv', 'term',
       'int_rate', 'installment', 'grade', 'sub_grade', 'emp_title',
       'emp_length', 'home_ownership', 'annual_inc',
       'verification_status', 'issue_d', 'loan_status', 'pymnt_plan',
       'url', 'desc', 'purpose', 'title', 'zip_code', 'addr_state', 'dti',
       'delinq_2yrs', 'earliest_cr_line', 'inq_last_6mths',
       'mths_since_last_delinq', 'mths_since_last_record', 'open_acc',
       'pub_rec', 'revol_bal', 'revol_util', 'total_acc',
       'initial_list_status', 'out_prncp', 'out_prncp_inv', 'total_pymnt',
       'total_pymnt_inv', 'total_rec_prncp', 'total_rec_int',
       'total_rec_late_fee', 'recoveries', 'collection_recovery_fee',
       'last_pymnt_d', 'last_pymnt_amnt', 'next_pymnt_d',
       'last_credit_pull_d', 'collections_12_mths_ex_med',
       'mths_since_last_major_derog', 'policy_code', 'application_type',
       'annual_inc_joint', 'dti_joint', 'verification_status_joint',
       'acc_now_delinq', 'tot_coll_amt', 'tot_cur_bal', 'open_acc_6m',
       'open_il_6m', 'open_il_12m', 'open_il_24m', 'mths_since_rcnt_il',
       'total_bal_il', 'il_util', 'open_rv_12m', 'open_rv_24m',
       'max_bal_bc', 'all_util', 'total_rev_hi_lim', 'inq_fi',
       'total_cu_tl', 'inq_last_12m'], dtype=object)

In [7]:
# Displaying column names with non missing cases and datatype
loan_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 421094 entries, 68444620 to 36271262
Data columns (total 73 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   member_id                    421094 non-null  int64
 1   loan_amnt                    421094 non-null  int64
 2   funded_amnt                  421094 non-null  int64
 3   funded_amnt_inv              421094 non-null  float64
 4   term                         421094 non-null  object
 5   int_rate                     421094 non-null  float64
 6   installment                  421094 non-null  float64
 7   grade                        421094 non-null  object
 8   sub_grade                    421094 non-null  object
 9   emp_title                    397220 non-null  object
 10  emp_length                   397277 non-null  object
 11  home_ownership               421094 non-null  object
 12  annual_inc                   421094 non-null  float64
 13  verification_status          421094 non-null  object
 14  issue_d                      421094 non-null  object
 15  loan_status                  421094 non-null  object
 16  pymnt_plan                   421094 non-null  object
 17  url                          421094 non-null  object
 18  desc                         45 non-null      object
 19  purpose                      421094 non-null  object
 20  title                        420962 non-null  object
 21  zip_code                     421094 non-null  object
 22  addr_state                   421094 non-null  object
 23  dti                          421094 non-null  float64
 24  delinq_2yrs                  421094 non-null  float64
 25  earliest_cr_line             421094 non-null  object
 26  inq_last_6mths               421094 non-null  float64
 27  mths_since_last_delinq       217133 non-null  float64
 28  mths_since_last_record       74415 non-null   float64
 29  open_acc                     421094 non-null  float64
 30  pub_rec                      421094 non-null  float64
 31  revol_bal                    421094 non-null  int64
 32  revol_util                   420932 non-null  float64
 33  total_acc                    421094 non-null  float64
 34  initial_list_status          421094 non-null  object
 35  out_prncp                    421094 non-null  float64
 36  out_prncp_inv                421094 non-null  float64
 37  total_pymnt                  421094 non-null  float64
 38  total_pymnt_inv              421094 non-null  float64
 39  total_rec_prncp              421094 non-null  float64
 40  total_rec_int                421094 non-null  float64
 41  total_rec_late_fee           421094 non-null  float64
 42  recoveries                   421094 non-null  float64
 43  collection_recovery_fee      421094 non-null  float64
 44  last_pymnt_d                 403811 non-null  object
 45  last_pymnt_amnt              421094 non-null  float64
 46  next_pymnt_d                 395337 non-null  object
 47  last_credit_pull_d           421083 non-null  object
 48  collections_12_mths_ex_med   421094 non-null  float64
 49  mths_since_last_major_derog  122729 non-null  float64
 50  policy_code                  421094 non-null  int64
 51  application_type             421094 non-null  object
 52  annual_inc_joint             511 non-null     float64
 53  dti_joint                    509 non-null     float64
 54  verification_status_joint    511 non-null     object
 55  acc_now_delinq               421094 non-null  float64
 56  tot_coll_amt                 421094 non-null  float64
 57  tot_cur_bal                  421094 non-null  float64
 58  open_acc_6m                  21372 non-null   float64
 59  open_il_6m                   21372 non-null   float64
 60  open_il_12m                  21372 non-null   float64
 61  open_il_24m                  21372 non-null   float64
 62  mths_since_rcnt_il           20810 non-null   float64
 63  total_bal_il                 21372 non-null   float64
 64  il_util                      18617 non-null   float64
 65  open_rv_12m                  21372 non-null   float64
 66  open_rv_24m                  21372 non-null   float64
 67  max_bal_bc                   21372 non-null   float64
 68  all_util                     21372 non-null   float64
 69  total_rev_hi_lim             421094 non-null  float64
 70  inq_fi                       21372 non-null   float64
 71  total_cu_tl                  21372 non-null   float64
 72  inq_last_12m                 21372 non-null   float64
dtypes: float64(45), int64(5), object(23)
memory usage: 237.7+ MB

Part of the code below is copied from the Data Preparation notebook, with minor adjustments. We have to perform the exact same data preprocessing, fine-classing, and coarse classing on the new data, in order to be able to calculate statistics for the exact same variables to the ones we used for training and testing the PD model.

# 2 General Preprocessing

## Discrete variables

In [8]:
dummy_columns = ['grade','sub_grade','home_ownership','verification_status',
                 'loan_status','purpose','addr_state','initial_list_status']

df_Dummies = pd.DataFrame()
for col in dummy_columns:
    dummy= pd.get_dummies(loan_data[col], prefix = col, prefix_sep = ':')
    df_Dummies = pd.concat([df_Dummies,dummy ], axis=1)
  #print(loan_data_Dummies.head())
  # = pd.concat([loan_data,loan_data_Dummies],axis = 1)
    
dummies_columns = ['grade','sub_grade','home_ownership','verification_status',
                 'loan_status','purpose','addr_state','initial_list_status']

In [9]:
#list of all dummy columns. 
df_Dummies.columns.values

array(['grade:A', 'grade:B', 'grade:C', 'grade:D', 'grade:E', 'grade:F',
       'grade:G', 'sub_grade:A1', 'sub_grade:A2', 'sub_grade:A3',
       'sub_grade:A4', 'sub_grade:A5', 'sub_grade:B1', 'sub_grade:B2',
       'sub_grade:B3', 'sub_grade:B4', 'sub_grade:B5', 'sub_grade:C1',
       'sub_grade:C2', 'sub_grade:C3', 'sub_grade:C4', 'sub_grade:C5',
       'sub_grade:D1', 'sub_grade:D2', 'sub_grade:D3', 'sub_grade:D4',
       'sub_grade:D5', 'sub_grade:E1', 'sub_grade:E2', 'sub_grade:E3',
       'sub_grade:E4', 'sub_grade:E5', 'sub_grade:F1', 'sub_grade:F2',
       'sub_grade:F3', 'sub_grade:F4', 'sub_grade:F5', 'sub_grade:G1',
       'sub_grade:G2', 'sub_grade:G3', 'sub_grade:G4', 'sub_grade:G5',
       'home_ownership:ANY', 'home_ownership:MORTGAGE',
       'home_ownership:OWN', 'home_ownership:RENT',
       'verification_status:Not Verified',
       'verification_status:Source Verified',
       'verification_status:Verified', 'loan_status:Charged Off',
       'loan_status:Current', 'loan_status:Default',
       'loan_status:Fully Paid', 'loan_status:In Grace Period',
       'loan_status:Issued', 'loan_status:Late (16-30 days)',
       'loan_status:Late (31-120 days)', 'purpose:car',
       'purpose:credit_card', 'purpose:debt_consolidation',
       'purpose:educational', 'purpose:home_improvement', 'purpose:house',
       'purpose:major_purchase', 'purpose:medical', 'purpose:moving',
       'purpose:other', 'purpose:renewable_energy',
       'purpose:small_business', 'purpose:vacation', 'purpose:wedding',
       'addr_state:AK', 'addr_state:AL', 'addr_state:AR', 'addr_state:AZ',
       'addr_state:CA', 'addr_state:CO', 'addr_state:CT', 'addr_state:DC',
       'addr_state:DE', 'addr_state:FL', 'addr_state:GA', 'addr_state:HI',
       'addr_state:IL', 'addr_state:IN', 'addr_state:KS', 'addr_state:KY',
       'addr_state:LA', 'addr_state:MA', 'addr_state:MD', 'addr_state:ME',
       'addr_state:MI', 'addr_state:MN', 'addr_state:MO', 'addr_state:MS',
       'addr_state:MT', 'addr_state:NC', 'addr_state:ND', 'addr_state:NE',
       'addr_state:NH', 'addr_state:NJ', 'addr_state:NM', 'addr_state:NV',
       'addr_state:NY', 'addr_state:OH', 'addr_state:OK', 'addr_state:OR',
       'addr_state:PA', 'addr_state:RI', 'addr_state:SC', 'addr_state:SD',
       'addr_state:TN', 'addr_state:TX', 'addr_state:UT', 'addr_state:VA',
       'addr_state:VT', 'addr_state:WA', 'addr_state:WI', 'addr_state:WV',
       'addr_state:WY', 'initial_list_status:f', 'initial_list_status:w'],
      dtype=object)

In [10]:
#merging dummy columns with the main dataset
loan_data = pd.concat([loan_data,df_Dummies],axis = 1)

## Continuous variables

In [11]:
#lets convert emp_length into integer
loan_data['emp_length'].unique()

array(['10+ years', '< 1 year', '5 years', '3 years', '4 years', nan,
       '2 years', '8 years', '9 years', '1 year', '6 years', '7 years'],
      dtype=object)

In [12]:
loan_data['emp_length_int']= loan_data['emp_length'].str.replace('\+ years','', regex=True)
loan_data['emp_length_int']= loan_data['emp_length_int'].str.replace('< 1 year',str(0), regex=True)
loan_data['emp_length_int']= loan_data['emp_length_int'].str.replace('n/a',str(0),regex=True)
loan_data['emp_length_int']= loan_data['emp_length_int'].str.replace(' years','', regex=True)
loan_data['emp_length_int']= loan_data['emp_length_int'].str.replace(' year','', regex=True)

In [13]:
loan_data['emp_length_int']=pd.to_numeric(loan_data['emp_length_int'])

In [14]:
# date variables not in dt format
loan_data['earliest_cr_line']

id
68444620    Feb-90
68547583    Jul-01
67849662    Jul-11
68506885    Dec-98
68341763    Aug-00
             ...
36371250    Sep-04
36441262    Mar-74
36271333    Sep-03
36490806    Oct-03
36271262    Dec-01
Name: earliest_cr_line, Length: 421094, dtype: object

In [15]:
#converting date column to format %b-%y : Apr-03 => 2003-04-03
loan_data['earliest_cr_line_date']=pd.to_datetime(loan_data['earliest_cr_line'],format = '%b-%y')
#calculating the months since a default date taken as 2017-12-01
diff_cr_line = pd.to_datetime('2017-12-01') - loan_data['earliest_cr_line_date']
loan_data['mths_since_earliest_cr_line'] = round(pd.to_numeric( diff_cr_line / np.timedelta64(1, 'M')))

In [16]:
loan_data['mths_since_earliest_cr_line'].describe()

count    421094.000000
mean        227.354876
std          98.123989
min        -612.000000
25%         167.000000
50%         212.000000
75%         277.000000
max         587.000000
Name: mths_since_earliest_cr_line, dtype: float64

In [17]:
#finding out why there are negative values in our dataset
m1 = loan_data['mths_since_earliest_cr_line']<0
loan_data.loc[m1,['earliest_cr_line','earliest_cr_line_date','mths_since_earliest_cr_line']].head()

         earliest_cr_line earliest_cr_line_date  mths_since_earliest_cr_line
id
68406292           Jan-57            2057-01-01                       -469.0
68506307           Aug-64            2064-08-01                       -560.0
68466525           Jul-68            2068-07-01                       -607.0
67858278           Jan-65            2065-01-01                       -565.0
68595008           Sep-64            2064-09-01                       -561.0

In [18]:
# it is neccessary to handle negative values. they are due to the 196x data read as 206x
# we take the maximum month difference to replace negative values
loan_data.loc[m1,'mths_since_earliest_cr_line'] = loan_data.loc[:,'mths_since_earliest_cr_line'].max()

In [19]:
#let's convert term column to integer format
loan_data['term']

id
68444620     60 months
68547583     36 months
67849662     36 months
68506885     60 months
68341763     60 months
               ...
36371250     36 months
36441262     36 months
36271333     60 months
36490806     60 months
36271262     36 months
Name: term, Length: 421094, dtype: object

In [20]:
loan_data['term_int'] = loan_data['term'].str.replace(' months', '').astype(int)
loan_data['term_int'].describe()

count    421094.000000
mean         43.860782
std          11.263533
min          36.000000
25%          36.000000
50%          36.000000
75%          60.000000
max          60.000000
Name: term_int, dtype: float64

In [21]:
# Assuming we are in December 2017
loan_data['issue_d_date'] = pd.to_datetime(loan_data['issue_d'], format = '%b-%y')

#calculating the month difference from 2017-12-01
# We calculate the difference between two dates in months, turn it to numeric datatype and round it.
diff_issue_d = pd.to_datetime('2017-12-01') - loan_data['issue_d_date']
loan_data['mths_since_issue_d'] = round(pd.to_numeric( diff_issue_d / np.timedelta64(1, 'M')))

# Showing some descriptive statisics for the values of a column.
loan_data['mths_since_issue_d'].describe()

count    421094.000000
mean         29.044629
std           3.458162
min          24.000000
25%          26.000000
50%          29.000000
75%          32.000000
max          35.000000
Name: mths_since_issue_d, dtype: float64

## Check missing values and clean

In [22]:
pd.options.display.max_rows = None
loan_data.isnull().sum().sort_values(ascending=False)

desc                                   421049
dti_joint                              420585
annual_inc_joint                       420583
verification_status_joint              420583
il_util                                402477
mths_since_rcnt_il                     400284
total_cu_tl                            399722
open_il_24m                            399722
inq_fi                                 399722
open_acc_6m                            399722
open_il_6m                             399722
open_il_12m                            399722
inq_last_12m                           399722
open_rv_24m                            399722
open_rv_12m                            399722
total_bal_il                           399722
all_util                               399722
max_bal_bc                             399722
mths_since_last_record                 346679
mths_since_last_major_derog            298365
mths_since_last_delinq                 203961
next_pymnt_d                            25757
emp_title                               23874
emp_length_int                          23817
emp_length                              23817
last_pymnt_d                            17283
revol_util                                162
title                                     132
last_credit_pull_d                         11
addr_state:CT                               0
addr_state:CO                               0
addr_state:DC                               0
addr_state:HI                               0
addr_state:DE                               0
addr_state:FL                               0
addr_state:GA                               0
addr_state:AZ                               0
addr_state:IL                               0
addr_state:CA                               0
member_id                                   0
addr_state:AR                               0
addr_state:AL                               0
home_ownership:OWN                          0
home_ownership:RENT                         0
verification_status:Not Verified            0
verification_status:Source Verified         0
verification_status:Verified                0
loan_status:Charged Off                     0
loan_status:Current                         0
loan_status:Default                         0
loan_status:Fully Paid                      0
loan_status:In Grace Period                 0
loan_status:Issued                          0
loan_status:Late (16-30 days)               0
loan_status:Late (31-120 days)              0
purpose:car                                 0
purpose:credit_card                         0
purpose:debt_consolidation                  0
purpose:educational                         0
purpose:home_improvement                    0
purpose:house                               0
purpose:major_purchase                      0
purpose:medical                             0
purpose:moving                              0
purpose:other                               0
purpose:renewable_energy                    0
purpose:small_business                      0
purpose:wedding                             0
addr_state:AK                               0
purpose:vacation                            0
addr_state:KS                               0
addr_state:IN                               0
addr_state:WA                               0
addr_state:RI                               0
addr_state:SC                               0
addr_state:SD                               0
addr_state:TN                               0
addr_state:TX                               0
addr_state:UT                               0
addr_state:VA                               0
addr_state:VT                               0
addr_state:WI                               0
addr_state:OR                               0
addr_state:WV                               0
addr_state:WY                               0
initial_list_status:f                       0
initial_list_status:w                       0
earliest_cr_line_date                       0
mths_since_earliest_cr_line                 0
term_int                                    0
issue_d_date                                0
addr_state:PA                               0
addr_state:OK                               0
home_ownership:ANY                          0
addr_state:MS                               0
addr_state:KY                               0
addr_state:LA                               0
addr_state:MA                               0
addr_state:MD                               0
addr_state:ME                               0
addr_state:MI                               0
addr_state:MN                               0
addr_state:MO                               0
addr_state:MT                               0
addr_state:OH                               0
addr_state:NC                               0
addr_state:ND                               0
addr_state:NE                               0
addr_state:NH                               0
addr_state:NJ                               0
addr_state:NM                               0
addr_state:NV                               0
addr_state:NY                               0
home_ownership:MORTGAGE                     0
sub_grade:E1                                0
sub_grade:G5                                0
total_rec_prncp                             0
pub_rec                                     0
revol_bal                                   0
total_acc                                   0
initial_list_status                         0
out_prncp                                   0
out_prncp_inv                               0
total_pymnt                                 0
total_pymnt_inv                             0
total_rec_int                               0
inq_last_6mths                              0
total_rec_late_fee                          0
recoveries                                  0
collection_recovery_fee                     0
last_pymnt_amnt                             0
collections_12_mths_ex_med                  0
policy_code                                 0
application_type                            0
acc_now_delinq                              0
open_acc                                    0
earliest_cr_line                            0
sub_grade:G4                                0
annual_inc                                  0
funded_amnt                                 0
funded_amnt_inv                             0
term                                        0
int_rate                                    0
installment                                 0
grade                                       0
sub_grade                                   0
home_ownership                              0
verification_status                         0
delinq_2yrs                                 0
issue_d                                     0
loan_status                                 0
pymnt_plan                                  0
url                                         0
purpose                                     0
zip_code                                    0
addr_state                                  0
dti                                         0
tot_coll_amt                                0
tot_cur_bal                                 0
total_rev_hi_lim                            0
sub_grade:E4                                0
sub_grade:D1                                0
sub_grade:D2                                0
sub_grade:D3                                0
sub_grade:D4                                0
sub_grade:D5                                0
loan_amnt                                   0
sub_grade:E2                                0
sub_grade:E3                                0
sub_grade:E5                                0
grade:A                                     0
sub_grade:F1                                0
sub_grade:F2                                0
sub_grade:F3                                0
sub_grade:F4                                0
sub_grade:F5                                0
sub_grade:G1                                0
sub_grade:G2                                0
sub_grade:G3                                0
sub_grade:C5                                0
sub_grade:C4                                0
sub_grade:C3                                0
sub_grade:C2                                0
grade:B                                     0
grade:C                                     0
grade:D                                     0
grade:E                                     0
grade:F                                     0
grade:G                                     0
sub_grade:A1                                0
sub_grade:A2                                0
sub_grade:A3                                0
sub_grade:A4                                0
sub_grade:A5                                0
sub_grade:B1                                0
sub_grade:B2                                0
sub_grade:B3                                0
sub_grade:B4                                0
sub_grade:B5                                0
sub_grade:C1                                0
mths_since_issue_d                          0
dtype: int64

In [23]:
# filling up the empty rows that will be used in our model.
# we use funded_amnt for the missing total_rev_hi_lim values
# fundedAmnt The total amount committed to that loan at that point in time.
loan_data['total_rev_hi_lim'].fillna(loan_data['funded_amnt'],inplace = True)

In [24]:
# for the missing values in annual_inc, mean value is considered.  
loan_data['annual_inc'].fillna(loan_data['annual_inc'].mean(),inplace = True)

In [25]:
# for the missing values below, we consider 0
loan_data['mths_since_earliest_cr_line'].fillna(0,inplace = True)
loan_data['acc_now_delinq'].fillna(0, inplace=True)
loan_data['total_acc'].fillna(0, inplace=True)
loan_data['pub_rec'].fillna(0, inplace=True)
loan_data['open_acc'].fillna(0, inplace=True)
loan_data['inq_last_6mths'].fillna(0, inplace=True)
loan_data['delinq_2yrs'].fillna(0, inplace=True)
loan_data['emp_length_int'].fillna(0, inplace=True)

## Preprocess discrete variables

We apply the same preprocessing as in Data preparation notebook.

In [30]:
df_inputs_prepr = loan_data.copy()
# Preprocessing - Input
#home_ownership
df_inputs_prepr['home_ownership:RENT_OTHER_NONE_ANY'] = sum ([df_inputs_prepr['home_ownership:RENT'], #df_inputs_prepr['home_ownership:OTHER'],
                                                            #df_inputs_prepr['home_ownership:NONE'], 
                                                            df_inputs_prepr['home_ownership:ANY'],])
# addr_state
if ['addr_state:ND'] in df_inputs_prepr.columns.values:
    pass
else:
    df_inputs_prepr['addr_state:ND'] = 0

#
# We create the following categories:
# 'ND' 'NE' 'IA' NV' 'FL' 'HI' 'AL'
# 'NM' 'VA'
# 'NY'
# 'OK' 'TN' 'MO' 'LA' 'MD' 'NC'
# 'CA'
# 'UT' 'KY' 'AZ' 'NJ'
# 'AR' 'MI' 'PA' 'OH' 'MN'
# 'RI' 'MA' 'DE' 'SD' 'IN'
# 'GA' 'WA' 'OR'
# 'WI' 'MT'
# 'TX'
# 'IL' 'CT'
# 'KS' 'SC' 'CO' 'VT' 'AK' 'MS'
# 'WV' 'NH' 'WY' 'DC' 'ME' 'ID'

# 'IA_NV_HI_ID_AL_FL' will be the reference category.

df_inputs_prepr['addr_state:ND_NE_IA_NV_FL_HI_AL'] = sum([df_inputs_prepr['addr_state:ND'], df_inputs_prepr['addr_state:NE'],
                                            #df_inputs_prepr['addr_state:IA'], 
                                            df_inputs_prepr['addr_state:NV'],
                                            df_inputs_prepr['addr_state:FL'], df_inputs_prepr['addr_state:HI'],
                                                        df_inputs_prepr['addr_state:AL']])

df_inputs_prepr['addr_state:NM_VA'] = sum([df_inputs_prepr['addr_state:NM'], df_inputs_prepr['addr_state:VA']])

df_inputs_prepr['addr_state:OK_TN_MO_LA_MD_NC'] = sum([df_inputs_prepr['addr_state:OK'], df_inputs_prepr['addr_state:TN'],
                                            df_inputs_prepr['addr_state:MO'], df_inputs_prepr['addr_state:LA'],
                                            df_inputs_prepr['addr_state:MD'], df_inputs_prepr['addr_state:NC']])

df_inputs_prepr['addr_state:UT_KY_AZ_NJ'] = sum([df_inputs_prepr['addr_state:UT'], df_inputs_prepr['addr_state:KY'],
                                            df_inputs_prepr['addr_state:AZ'], df_inputs_prepr['addr_state:NJ']])

df_inputs_prepr['addr_state:AR_MI_PA_OH_MN'] = sum([df_inputs_prepr['addr_state:AR'], df_inputs_prepr['addr_state:MI'],
                                            df_inputs_prepr['addr_state:PA'], df_inputs_prepr['addr_state:OH'],
                                            df_inputs_prepr['addr_state:MN']])

df_inputs_prepr['addr_state:RI_MA_DE_SD_IN'] = sum([df_inputs_prepr['addr_state:RI'], df_inputs_prepr['addr_state:MA'],
                                            df_inputs_prepr['addr_state:DE'], df_inputs_prepr['addr_state:SD'],
                                            df_inputs_prepr['addr_state:IN']])

df_inputs_prepr['addr_state:GA_WA_OR'] = sum([df_inputs_prepr['addr_state:GA'], df_inputs_prepr['addr_state:WA'],
                                            df_inputs_prepr['addr_state:OR']])

df_inputs_prepr['addr_state:WI_MT'] = sum([df_inputs_prepr['addr_state:WI'], df_inputs_prepr['addr_state:MT']])

df_inputs_prepr['addr_state:IL_CT'] = sum([df_inputs_prepr['addr_state:IL'], df_inputs_prepr['addr_state:CT']])

df_inputs_prepr['addr_state:KS_SC_CO_VT_AK_MS'] = sum([df_inputs_prepr['addr_state:KS'], df_inputs_prepr['addr_state:SC'],
                                            df_inputs_prepr['addr_state:CO'], df_inputs_prepr['addr_state:VT'],
                                            df_inputs_prepr['addr_state:AK'], df_inputs_prepr['addr_state:MS']])

df_inputs_prepr['addr_state:WV_NH_WY_DC_ME_ID'] = sum([df_inputs_prepr['addr_state:WV'], df_inputs_prepr['addr_state:NH'],
                                            df_inputs_prepr['addr_state:WY'], df_inputs_prepr['addr_state:DC'],
                                            df_inputs_prepr['addr_state:ME'], 
                                            #df_inputs_prepr['addr_state:ID']
                                            ])

# purpose
df_inputs_prepr['purpose:educ__sm_b__wedd__ren_en__mov__house'] = sum([df_inputs_prepr['purpose:educational'], df_inputs_prepr['purpose:small_business'],
                                                              df_inputs_prepr['purpose:wedding'], df_inputs_prepr['purpose:renewable_energy'],
                                                              df_inputs_prepr['purpose:moving'], df_inputs_prepr['purpose:house']])
df_inputs_prepr['purpose:oth__med__vacation'] = sum([df_inputs_prepr['purpose:other'], df_inputs_prepr['purpose:medical'],
                                          df_inputs_prepr['purpose:vacation']])
df_inputs_prepr['purpose:major_purch__car__home_impr'] = sum([df_inputs_prepr['purpose:major_purchase'], df_inputs_prepr['purpose:car'],
                                                      df_inputs_prepr['purpose:home_improvement']])

# term
df_inputs_prepr['term:36'] = np.where((df_inputs_prepr['term_int']==36),1,0)
df_inputs_prepr['term:60'] = np.where((df_inputs_prepr['term_int']==60),1,0)

# emp length
df_inputs_prepr['emp_length:0'] = np.where(df_inputs_prepr['emp_length_int'].isin([0]), 1, 0)
df_inputs_prepr['emp_length:1'] = np.where(df_inputs_prepr['emp_length_int'].isin([1]), 1, 0)
df_inputs_prepr['emp_length:2-4'] = np.where(df_inputs_prepr['emp_length_int'].isin(range(2, 5)), 1, 0)
df_inputs_prepr['emp_length:5-6'] = np.where(df_inputs_prepr['emp_length_int'].isin(range(5, 7)), 1, 0)
df_inputs_prepr['emp_length:7-9'] = np.where(df_inputs_prepr['emp_length_int'].isin(range(7, 10)), 1, 0)
df_inputs_prepr['emp_length:10'] = np.where(df_inputs_prepr['emp_length_int'].isin([10]), 1, 0)

# int rate
df_inputs_prepr['int_rate:<9.548'] = np.where((df_inputs_prepr['int_rate'] <= 9.548), 1, 0)
df_inputs_prepr['int_rate:9.548-12.025'] = np.where((df_inputs_prepr['int_rate'] > 9.548) & (df_inputs_prepr['int_rate'] <= 12.025), 1, 0)
df_inputs_prepr['int_rate:12.025-15.74'] = np.where((df_inputs_prepr['int_rate'] > 12.025) & (df_inputs_prepr['int_rate'] <= 15.74), 1, 0)
df_inputs_prepr['int_rate:15.74-20.281'] = np.where((df_inputs_prepr['int_rate'] > 15.74) & (df_inputs_prepr['int_rate'] <= 20.281), 1, 0)
df_inputs_prepr['int_rate:>20.281'] = np.where((df_inputs_prepr['int_rate'] > 20.281), 1, 0)

# mths_since_earliest_cr_Line
df_inputs_prepr['mths_since_earliest_cr_line:<140'] = np.where(df_inputs_prepr['mths_since_earliest_cr_line'].isin(range(140)), 1, 0)
df_inputs_prepr['mths_since_earliest_cr_line:141-164'] = np.where(df_inputs_prepr['mths_since_earliest_cr_line'].isin(range(140, 165)), 1, 0)
df_inputs_prepr['mths_since_earliest_cr_line:165-247'] = np.where(df_inputs_prepr['mths_since_earliest_cr_line'].isin(range(165, 248)), 1, 0)
df_inputs_prepr['mths_since_earliest_cr_line:248-270'] = np.where(df_inputs_prepr['mths_since_earliest_cr_line'].isin(range(248, 271)), 1, 0)
df_inputs_prepr['mths_since_earliest_cr_line:271-352'] = np.where(df_inputs_prepr['mths_since_earliest_cr_line'].isin(range(271, 353)), 1, 0)
df_inputs_prepr['mths_since_earliest_cr_line:>352'] = np.where(df_inputs_prepr['mths_since_earliest_cr_line'].isin(range(353, int(df_inputs_prepr['mths_since_earliest_cr_line'].max()))), 1, 0)

# delinq_2yrs
df_inputs_prepr['delinq_2yrs:0'] = np.where((df_inputs_prepr['delinq_2yrs'] == 0), 1, 0)
df_inputs_prepr['delinq_2yrs:1-3'] = np.where((df_inputs_prepr['delinq_2yrs'] >= 1) & (df_inputs_prepr['delinq_2yrs'] <= 3), 1, 0)
df_inputs_prepr['delinq_2yrs:>=4'] = np.where((df_inputs_prepr['delinq_2yrs'] >= 9), 1, 0)

# inq_last_6mths
df_inputs_prepr['inq_last_6mths:0'] = np.where((df_inputs_prepr['inq_last_6mths'] == 0), 1, 0)
df_inputs_prepr['inq_last_6mths:1-2'] = np.where((df_inputs_prepr['inq_last_6mths'] >= 1) & (df_inputs_prepr['inq_last_6mths'] <= 2), 1, 0)
df_inputs_prepr['inq_last_6mths:3-6'] = np.where((df_inputs_prepr['inq_last_6mths'] >= 3) & (df_inputs_prepr['inq_last_6mths'] <= 6), 1, 0)
df_inputs_prepr['inq_last_6mths:>6'] = np.where((df_inputs_prepr['inq_last_6mths'] > 6), 1, 0)

# open acc
df_inputs_prepr['open_acc:0'] = np.where((df_inputs_prepr['open_acc'] == 0), 1, 0)
df_inputs_prepr['open_acc:1-3'] = np.where((df_inputs_prepr['open_acc'] >= 1) & (df_inputs_prepr['open_acc'] <= 3), 1, 0)
df_inputs_prepr['open_acc:4-12'] = np.where((df_inputs_prepr['open_acc'] >= 4) & (df_inputs_prepr['open_acc'] <= 12), 1, 0)
df_inputs_prepr['open_acc:13-17'] = np.where((df_inputs_prepr['open_acc'] >= 13) & (df_inputs_prepr['open_acc'] <= 17), 1, 0)
df_inputs_prepr['open_acc:18-22'] = np.where((df_inputs_prepr['open_acc'] >= 18) & (df_inputs_prepr['open_acc'] <= 22), 1, 0)
df_inputs_prepr['open_acc:23-25'] = np.where((df_inputs_prepr['open_acc'] >= 23) & (df_inputs_prepr['open_acc'] <= 25), 1, 0)
df_inputs_prepr['open_acc:26-30'] = np.where((df_inputs_prepr['open_acc'] >= 26) & (df_inputs_prepr['open_acc'] <= 30), 1, 0)
df_inputs_prepr['open_acc:>=31'] = np.where((df_inputs_prepr['open_acc'] >= 31), 1, 0)

# pub rec
df_inputs_prepr['pub_rec:0-2'] = np.where((df_inputs_prepr['pub_rec'] >= 0) & (df_inputs_prepr['pub_rec'] <= 2), 1, 0)
df_inputs_prepr['pub_rec:3-4'] = np.where((df_inputs_prepr['pub_rec'] >= 3) & (df_inputs_prepr['pub_rec'] <= 4), 1, 0)
df_inputs_prepr['pub_rec:>=5'] = np.where((df_inputs_prepr['pub_rec'] >= 5), 1, 0)

# total_acc
df_inputs_prepr['total_acc:<=27'] = np.where((df_inputs_prepr['total_acc'] <= 27), 1, 0)
df_inputs_prepr['total_acc:28-51'] = np.where((df_inputs_prepr['total_acc'] >= 28) & (df_inputs_prepr['total_acc'] <= 51), 1, 0)
df_inputs_prepr['total_acc:>=52'] = np.where((df_inputs_prepr['total_acc'] >= 52), 1, 0)

# acc_now_delinq 
df_inputs_prepr['acc_now_delinq:0'] = np.where((df_inputs_prepr['acc_now_delinq'] == 0), 1, 0)
df_inputs_prepr['acc_now_delinq:>=1'] = np.where((df_inputs_prepr['acc_now_delinq'] >= 1), 1, 0)

# total_rev_hi 
df_inputs_prepr['total_rev_hi_lim:<=5K'] = np.where((df_inputs_prepr['total_rev_hi_lim'] <= 5000), 1, 0)
df_inputs_prepr['total_rev_hi_lim:5K-10K'] = np.where((df_inputs_prepr['total_rev_hi_lim'] > 5000) & (df_inputs_prepr['total_rev_hi_lim'] <= 10000), 1, 0)
df_inputs_prepr['total_rev_hi_lim:10K-20K'] = np.where((df_inputs_prepr['total_rev_hi_lim'] > 10000) & (df_inputs_prepr['total_rev_hi_lim'] <= 20000), 1, 0)
df_inputs_prepr['total_rev_hi_lim:20K-30K'] = np.where((df_inputs_prepr['total_rev_hi_lim'] > 20000) & (df_inputs_prepr['total_rev_hi_lim'] <= 30000), 1, 0)
df_inputs_prepr['total_rev_hi_lim:30K-40K'] = np.where((df_inputs_prepr['total_rev_hi_lim'] > 30000) & (df_inputs_prepr['total_rev_hi_lim'] <= 40000), 1, 0)
df_inputs_prepr['total_rev_hi_lim:40K-55K'] = np.where((df_inputs_prepr['total_rev_hi_lim'] > 40000) & (df_inputs_prepr['total_rev_hi_lim'] <= 55000), 1, 0)
df_inputs_prepr['total_rev_hi_lim:55K-95K'] = np.where((df_inputs_prepr['total_rev_hi_lim'] > 55000) & (df_inputs_prepr['total_rev_hi_lim'] <= 95000), 1, 0)
df_inputs_prepr['total_rev_hi_lim:>95K'] = np.where((df_inputs_prepr['total_rev_hi_lim'] > 95000), 1, 0)

# annual inc
df_inputs_prepr['annual_inc:<20K'] = np.where((df_inputs_prepr['annual_inc'] <= 20000), 1, 0)
df_inputs_prepr['annual_inc:20K-30K'] = np.where((df_inputs_prepr['annual_inc'] > 20000) & (df_inputs_prepr['annual_inc'] <= 30000), 1, 0)
df_inputs_prepr['annual_inc:30K-40K'] = np.where((df_inputs_prepr['annual_inc'] > 30000) & (df_inputs_prepr['annual_inc'] <= 40000), 1, 0)
df_inputs_prepr['annual_inc:40K-50K'] = np.where((df_inputs_prepr['annual_inc'] > 40000) & (df_inputs_prepr['annual_inc'] <= 50000), 1, 0)
df_inputs_prepr['annual_inc:50K-60K'] = np.where((df_inputs_prepr['annual_inc'] > 50000) & (df_inputs_prepr['annual_inc'] <= 60000), 1, 0)
df_inputs_prepr['annual_inc:60K-70K'] = np.where((df_inputs_prepr['annual_inc'] > 60000) & (df_inputs_prepr['annual_inc'] <= 70000), 1, 0)
df_inputs_prepr['annual_inc:70K-80K'] = np.where((df_inputs_prepr['annual_inc'] > 70000) & (df_inputs_prepr['annual_inc'] <= 80000), 1, 0)
df_inputs_prepr['annual_inc:80K-90K'] = np.where((df_inputs_prepr['annual_inc'] > 80000) & (df_inputs_prepr['annual_inc'] <= 90000), 1, 0)
df_inputs_prepr['annual_inc:90K-100K'] = np.where((df_inputs_prepr['annual_inc'] > 90000) & (df_inputs_prepr['annual_inc'] <= 100000), 1, 0)
df_inputs_prepr['annual_inc:100K-120K'] = np.where((df_inputs_prepr['annual_inc'] > 100000) & (df_inputs_prepr['annual_inc'] <= 120000), 1, 0)
df_inputs_prepr['annual_inc:120K-140K'] = np.where((df_inputs_prepr['annual_inc'] > 120000) & (df_inputs_prepr['annual_inc'] <= 140000), 1, 0)
df_inputs_prepr['annual_inc:>140K'] = np.where((df_inputs_prepr['annual_inc'] > 140000), 1, 0)

# mths since last delinq
df_inputs_prepr['mths_since_last_delinq:Missing'] = np.where((df_inputs_prepr['mths_since_last_delinq'].isnull()), 1, 0)
df_inputs_prepr['mths_since_last_delinq:0-3'] = np.where((df_inputs_prepr['mths_since_last_delinq'] >= 0) & (df_inputs_prepr['mths_since_last_delinq'] <= 3), 1, 0)
df_inputs_prepr['mths_since_last_delinq:4-30'] = np.where((df_inputs_prepr['mths_since_last_delinq'] >= 4) & (df_inputs_prepr['mths_since_last_delinq'] <= 30), 1, 0)
df_inputs_prepr['mths_since_last_delinq:31-56'] = np.where((df_inputs_prepr['mths_since_last_delinq'] >= 31) & (df_inputs_prepr['mths_since_last_delinq'] <= 56), 1, 0)
df_inputs_prepr['mths_since_last_delinq:>=57'] = np.where((df_inputs_prepr['mths_since_last_delinq'] >= 57), 1, 0)

# dti
df_inputs_prepr['dti:<=1.4'] = np.where((df_inputs_prepr['dti'] <= 1.4), 1, 0)
df_inputs_prepr['dti:1.4-3.5'] = np.where((df_inputs_prepr['dti'] > 1.4) & (df_inputs_prepr['dti'] <= 3.5), 1, 0)
df_inputs_prepr['dti:3.5-7.7'] = np.where((df_inputs_prepr['dti'] > 3.5) & (df_inputs_prepr['dti'] <= 7.7), 1, 0)
df_inputs_prepr['dti:7.7-10.5'] = np.where((df_inputs_prepr['dti'] > 7.7) & (df_inputs_prepr['dti'] <= 10.5), 1, 0)
df_inputs_prepr['dti:10.5-16.1'] = np.where((df_inputs_prepr['dti'] > 10.5) & (df_inputs_prepr['dti'] <= 16.1), 1, 0)
df_inputs_prepr['dti:16.1-20.3'] = np.where((df_inputs_prepr['dti'] > 16.1) & (df_inputs_prepr['dti'] <= 20.3), 1, 0)
df_inputs_prepr['dti:20.3-21.7'] = np.where((df_inputs_prepr['dti'] > 20.3) & (df_inputs_prepr['dti'] <= 21.7), 1, 0)
df_inputs_prepr['dti:21.7-22.4'] = np.where((df_inputs_prepr['dti'] > 21.7) & (df_inputs_prepr['dti'] <= 22.4), 1, 0)
df_inputs_prepr['dti:22.4-35'] = np.where((df_inputs_prepr['dti'] > 22.4) & (df_inputs_prepr['dti'] <= 35), 1, 0)
df_inputs_prepr['dti:>35'] = np.where((df_inputs_prepr['dti'] > 35), 1, 0)

# mths_since_last_record
# Categories: 'Missing', '0-2', '3-20', '21-31', '32-80', '81-86', '>86'
df_inputs_prepr['mths_since_last_record:Missing'] = np.where((df_inputs_prepr['mths_since_last_record'].isnull()), 1, 0)
df_inputs_prepr['mths_since_last_record:0-2'] = np.where((df_inputs_prepr['mths_since_last_record'] >= 0) & (df_inputs_prepr['mths_since_last_record'] <= 2), 1, 0)
df_inputs_prepr['mths_since_last_record:3-20'] = np.where((df_inputs_prepr['mths_since_last_record'] >= 3) & (df_inputs_prepr['mths_since_last_record'] <= 20), 1, 0)
df_inputs_prepr['mths_since_last_record:21-31'] = np.where((df_inputs_prepr['mths_since_last_record'] >= 21) & (df_inputs_prepr['mths_since_last_record'] <= 31), 1, 0)
df_inputs_prepr['mths_since_last_record:32-80'] = np.where((df_inputs_prepr['mths_since_last_record'] >= 32) & (df_inputs_prepr['mths_since_last_record'] <= 80), 1, 0)
df_inputs_prepr['mths_since_last_record:81-86'] = np.where((df_inputs_prepr['mths_since_last_record'] >= 81) & (df_inputs_prepr['mths_since_last_record'] <= 86), 1, 0)
df_inputs_prepr['mths_since_last_record:>=86'] = np.where((df_inputs_prepr['mths_since_last_record'] > 86), 1, 0)

In [31]:
# test dataset
loan_data_2015= df_inputs_prepr
loan_data_2015.columns.values

array(['member_id', 'loan_amnt', 'funded_amnt', 'funded_amnt_inv', 'term',
       'int_rate', 'installment', 'grade', 'sub_grade', 'emp_title',
       'emp_length', 'home_ownership', 'annual_inc',
       'verification_status', 'issue_d', 'loan_status', 'pymnt_plan',
       'url', 'desc', 'purpose', 'title', 'zip_code', 'addr_state', 'dti',
       'delinq_2yrs', 'earliest_cr_line', 'inq_last_6mths',
       'mths_since_last_delinq', 'mths_since_last_record', 'open_acc',
       'pub_rec', 'revol_bal', 'revol_util', 'total_acc',
       'initial_list_status', 'out_prncp', 'out_prncp_inv', 'total_pymnt',
       'total_pymnt_inv', 'total_rec_prncp', 'total_rec_int',
       'total_rec_late_fee', 'recoveries', 'collection_recovery_fee',
       'last_pymnt_d', 'last_pymnt_amnt', 'next_pymnt_d',
       'last_credit_pull_d', 'collections_12_mths_ex_med',
       'mths_since_last_major_derog', 'policy_code', 'application_type',
       'annual_inc_joint', 'dti_joint', 'verification_status_joint',
       'acc_now_delinq', 'tot_coll_amt', 'tot_cur_bal', 'open_acc_6m',
       'open_il_6m', 'open_il_12m', 'open_il_24m', 'mths_since_rcnt_il',
       'total_bal_il', 'il_util', 'open_rv_12m', 'open_rv_24m',
       'max_bal_bc', 'all_util', 'total_rev_hi_lim', 'inq_fi',
       'total_cu_tl', 'inq_last_12m', 'grade:A', 'grade:B', 'grade:C',
       'grade:D', 'grade:E', 'grade:F', 'grade:G', 'sub_grade:A1',
       'sub_grade:A2', 'sub_grade:A3', 'sub_grade:A4', 'sub_grade:A5',
       'sub_grade:B1', 'sub_grade:B2', 'sub_grade:B3', 'sub_grade:B4',
       'sub_grade:B5', 'sub_grade:C1', 'sub_grade:C2', 'sub_grade:C3',
       'sub_grade:C4', 'sub_grade:C5', 'sub_grade:D1', 'sub_grade:D2',
       'sub_grade:D3', 'sub_grade:D4', 'sub_grade:D5', 'sub_grade:E1',
       'sub_grade:E2', 'sub_grade:E3', 'sub_grade:E4', 'sub_grade:E5',
       'sub_grade:F1', 'sub_grade:F2', 'sub_grade:F3', 'sub_grade:F4',
       'sub_grade:F5', 'sub_grade:G1', 'sub_grade:G2', 'sub_grade:G3',
       'sub_grade:G4', 'sub_grade:G5', 'home_ownership:ANY',
       'home_ownership:MORTGAGE', 'home_ownership:OWN',
       'home_ownership:RENT', 'verification_status:Not Verified',
       'verification_status:Source Verified',
       'verification_status:Verified', 'loan_status:Charged Off',
       'loan_status:Current', 'loan_status:Default',
       'loan_status:Fully Paid', 'loan_status:In Grace Period',
       'loan_status:Issued', 'loan_status:Late (16-30 days)',
       'loan_status:Late (31-120 days)', 'purpose:car',
       'purpose:credit_card', 'purpose:debt_consolidation',
       'purpose:educational', 'purpose:home_improvement', 'purpose:house',
       'purpose:major_purchase', 'purpose:medical', 'purpose:moving',
       'purpose:other', 'purpose:renewable_energy',
       'purpose:small_business', 'purpose:vacation', 'purpose:wedding',
       'addr_state:AK', 'addr_state:AL', 'addr_state:AR', 'addr_state:AZ',
       'addr_state:CA', 'addr_state:CO', 'addr_state:CT', 'addr_state:DC',
       'addr_state:DE', 'addr_state:FL', 'addr_state:GA', 'addr_state:HI',
       'addr_state:IL', 'addr_state:IN', 'addr_state:KS', 'addr_state:KY',
       'addr_state:LA', 'addr_state:MA', 'addr_state:MD', 'addr_state:ME',
       'addr_state:MI', 'addr_state:MN', 'addr_state:MO', 'addr_state:MS',
       'addr_state:MT', 'addr_state:NC', 'addr_state:ND', 'addr_state:NE',
       'addr_state:NH', 'addr_state:NJ', 'addr_state:NM', 'addr_state:NV',
       'addr_state:NY', 'addr_state:OH', 'addr_state:OK', 'addr_state:OR',
       'addr_state:PA', 'addr_state:RI', 'addr_state:SC', 'addr_state:SD',
       'addr_state:TN', 'addr_state:TX', 'addr_state:UT', 'addr_state:VA',
       'addr_state:VT', 'addr_state:WA', 'addr_state:WI', 'addr_state:WV',
       'addr_state:WY', 'initial_list_status:f', 'initial_list_status:w',
       'emp_length_int', 'earliest_cr_line_date',
       'mths_since_earliest_cr_line', 'term_int', 'issue_d_date',
       'mths_since_issue_d', 'home_ownership:RENT_OTHER_NONE_ANY',
       'addr_state:ND_NE_IA_NV_FL_HI_AL', 'addr_state:NM_VA',
       'addr_state:OK_TN_MO_LA_MD_NC', 'addr_state:UT_KY_AZ_NJ',
       'addr_state:AR_MI_PA_OH_MN', 'addr_state:RI_MA_DE_SD_IN',
       'addr_state:GA_WA_OR', 'addr_state:WI_MT', 'addr_state:IL_CT',
       'addr_state:KS_SC_CO_VT_AK_MS', 'addr_state:WV_NH_WY_DC_ME_ID',
       'purpose:educ__sm_b__wedd__ren_en__mov__house',
       'purpose:oth__med__vacation',
       'purpose:major_purch__car__home_impr', 'term:36', 'term:60',
       'emp_length:0', 'emp_length:1', 'emp_length:2-4', 'emp_length:5-6',
       'emp_length:7-9', 'emp_length:10', 'int_rate:<9.548',
       'int_rate:9.548-12.025', 'int_rate:12.025-15.74',
       'int_rate:15.74-20.281', 'int_rate:>20.281',
       'mths_since_earliest_cr_line:<140',
       'mths_since_earliest_cr_line:141-164',
       'mths_since_earliest_cr_line:165-247',
       'mths_since_earliest_cr_line:248-270',
       'mths_since_earliest_cr_line:271-352',
       'mths_since_earliest_cr_line:>352', 'delinq_2yrs:0',
       'delinq_2yrs:1-3', 'delinq_2yrs:>=4', 'inq_last_6mths:0',
       'inq_last_6mths:1-2', 'inq_last_6mths:3-6', 'inq_last_6mths:>6',
       'open_acc:0', 'open_acc:1-3', 'open_acc:4-12', 'open_acc:13-17',
       'open_acc:18-22', 'open_acc:23-25', 'open_acc:26-30',
       'open_acc:>=31', 'pub_rec:0-2', 'pub_rec:3-4', 'pub_rec:>=5',
       'total_acc:<=27', 'total_acc:28-51', 'total_acc:>=52',
       'acc_now_delinq:0', 'acc_now_delinq:>=1', 'total_rev_hi_lim:<=5K',
       'total_rev_hi_lim:5K-10K', 'total_rev_hi_lim:10K-20K',
       'total_rev_hi_lim:20K-30K', 'total_rev_hi_lim:30K-40K',
       'total_rev_hi_lim:40K-55K', 'total_rev_hi_lim:55K-95K',
       'total_rev_hi_lim:>95K', 'annual_inc:<20K', 'annual_inc:20K-30K',
       'annual_inc:30K-40K', 'annual_inc:40K-50K', 'annual_inc:50K-60K',
       'annual_inc:60K-70K', 'annual_inc:70K-80K', 'annual_inc:80K-90K',
       'annual_inc:90K-100K', 'annual_inc:100K-120K',
       'annual_inc:120K-140K', 'annual_inc:>140K',
       'mths_since_last_delinq:Missing', 'mths_since_last_delinq:0-3',
       'mths_since_last_delinq:4-30', 'mths_since_last_delinq:31-56',
       'mths_since_last_delinq:>=57', 'dti:<=1.4', 'dti:1.4-3.5',
       'dti:3.5-7.7', 'dti:7.7-10.5', 'dti:10.5-16.1', 'dti:16.1-20.3',
       'dti:20.3-21.7', 'dti:21.7-22.4', 'dti:22.4-35', 'dti:>35',
       'mths_since_last_record:Missing', 'mths_since_last_record:0-2',
       'mths_since_last_record:3-20', 'mths_since_last_record:21-31',
       'mths_since_last_record:32-80', 'mths_since_last_record:81-86',
       'mths_since_last_record:>=86'], dtype=object)

In [32]:
# We commented on some features, the coefficients for all or almost all of the dummy variables for which,
# are not statistically significant.
# Refined variables
features_all = ['grade:A',
'grade:B',
'grade:C',
'grade:D',
'grade:E',
'grade:F',
'grade:G',
'home_ownership:RENT_OTHER_NONE_ANY',
'home_ownership:OWN',
'home_ownership:MORTGAGE',
'addr_state:ND_NE_IA_NV_FL_HI_AL',
'addr_state:NM_VA',
'addr_state:NY',
'addr_state:OK_TN_MO_LA_MD_NC',
'addr_state:CA',
'addr_state:UT_KY_AZ_NJ',
'addr_state:AR_MI_PA_OH_MN',
'addr_state:RI_MA_DE_SD_IN',
'addr_state:GA_WA_OR',
'addr_state:WI_MT',
'addr_state:TX',
'addr_state:IL_CT',
'addr_state:KS_SC_CO_VT_AK_MS',
'addr_state:WV_NH_WY_DC_ME_ID',
'verification_status:Not Verified',
'verification_status:Source Verified',
'verification_status:Verified',
'purpose:educ__sm_b__wedd__ren_en__mov__house',
'purpose:credit_card',
'purpose:debt_consolidation',
'purpose:oth__med__vacation',
'purpose:major_purch__car__home_impr',
'initial_list_status:f',
'initial_list_status:w',
'term:36',
'term:60',
'emp_length:0',
'emp_length:1',
'emp_length:2-4',
'emp_length:5-6',
'emp_length:7-9',
'emp_length:10',
'int_rate:<9.548',
'int_rate:9.548-12.025',
'int_rate:12.025-15.74',
'int_rate:15.74-20.281',
'int_rate:>20.281',
#'mths_since_earliest_cr_line:<140',
#'mths_since_earliest_cr_line:141-164',
#'mths_since_earliest_cr_line:165-247',
#'mths_since_earliest_cr_line:248-270',
#'mths_since_earliest_cr_line:271-352',
#'mths_since_earliest_cr_line:>352',
#'delinq_2yrs:0',
#'delinq_2yrs:1-3',
#'delinq_2yrs:>=4',
'inq_last_6mths:0',
'inq_last_6mths:1-2',
'inq_last_6mths:3-6',
'inq_last_6mths:>6',
#'open_acc:0',
#'open_acc:1-3',
#'open_acc:4-12',
#'open_acc:13-17',
#'open_acc:18-22',
#'open_acc:23-25',
#'open_acc:26-30',
#'open_acc:>=31',
'pub_rec:0-2',
'pub_rec:3-4',
'pub_rec:>=5',
#'total_acc:<=27',
#'total_acc:28-51',
#'total_acc:>=52',
'acc_now_delinq:0',
'acc_now_delinq:>=1',
'total_rev_hi_lim:<=5K',
'total_rev_hi_lim:5K-10K',
'total_rev_hi_lim:10K-20K',
'total_rev_hi_lim:20K-30K',
'total_rev_hi_lim:30K-40K',
'total_rev_hi_lim:40K-55K',
'total_rev_hi_lim:55K-95K',
'total_rev_hi_lim:>95K',
'annual_inc:<20K',
'annual_inc:20K-30K',
'annual_inc:30K-40K',
'annual_inc:40K-50K',
'annual_inc:50K-60K',
'annual_inc:60K-70K',
'annual_inc:70K-80K',
'annual_inc:80K-90K',
'annual_inc:90K-100K',
'annual_inc:100K-120K',
'annual_inc:120K-140K',
'annual_inc:>140K',
'dti:<=1.4',
'dti:1.4-3.5',
'dti:3.5-7.7',
'dti:7.7-10.5',
'dti:10.5-16.1',
'dti:16.1-20.3',
'dti:20.3-21.7',
'dti:21.7-22.4',
'dti:22.4-35',
'dti:>35',
#'mths_since_last_delinq:Missing',
#'mths_since_last_delinq:0-3',
#'mths_since_last_delinq:4-30',
#'mths_since_last_delinq:31-56',
#'mths_since_last_delinq:>=57',
#'mths_since_last_record:Missing',
#'mths_since_last_record:0-2',
#'mths_since_last_record:3-20',
#'mths_since_last_record:21-31',
#'mths_since_last_record:32-80',
#'mths_since_last_record:81-86',
#'mths_since_last_record:>=86',
]

In [33]:

ref_categories = ['grade:G',
'home_ownership:RENT_OTHER_NONE_ANY',
'addr_state:ND_NE_IA_NV_FL_HI_AL',
'verification_status:Verified',
'purpose:educ__sm_b__wedd__ren_en__mov__house',
'initial_list_status:f',
'term:60',
'emp_length:0',
'int_rate:>20.281',
#'mths_since_earliest_cr_line:<140',
#'delinq_2yrs:>=4',
'inq_last_6mths:>6',
#'open_acc:0',
'pub_rec:0-2',
#'total_acc:<=27',
'acc_now_delinq:0',
'total_rev_hi_lim:<=5K',
'annual_inc:<20K',
'dti:>35'
#'mths_since_last_delinq:0-3',
#'mths_since_last_record:0-2'
]

In [34]:
inputs_2015_With_ref_cat = loan_data_2015.loc[:,features_all]

In [35]:
# loading values of df in a new dataframe.   
inputs_train_With_ref_categories = inputs_train.loc[: ,features_all]
 
inputs_train_With_ref_categories.head()

,grade:A,grade:B,grade:C,grade:D,grade:E,grade:F,grade:G,home_ownership:RENT_OTHER_NONE_ANY,home_ownership:OWN,home_ownership:MORTGAGE,...,dti:<=1.4,dti:1.4-3.5,dti:3.5-7.7,dti:7.7-10.5,dti:10.5-16.1,dti:16.1-20.3,dti:20.3-21.7,dti:21.7-22.4,dti:22.4-35,dti:>35
427211,1,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,1,0,0
206088,0,0,1,0,0,0,0,0,0,1,...,0,0,1,0,0,0,0,0,0,0
136020,1,0,0,0,0,0,0,0,0,1,...,0,0,0,0,1,0,0,0,0,0
412305,0,0,0,1,0,0,0,1,0,0,...,0,0,0,0,1,0,0,0,0,0
36159,0,0,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,1,0

In [36]:
inputs_2015_With_ref_cat.shape

(421094, 86)

# 3 Calculating scores from a score card

In [37]:
df_scorecard = pd.read_csv ('df_scorecard.csv',index_col= 0)

In [38]:
df_scorecard

,index,Feature name,Coefficients,p_values,Original feature name,Score - Calculation,Score - Preliminary,Score - Final,Difference
0,0,Intercept,-0.814514,NaN,Intercept,329.921225,330.0,330.0,0.078775
1,1,grade:A,0.439412,4.198075e-07,grade,35.389717,35.0,35.0,-0.389717
2,2,grade:B,0.552751,1.464341e-21,grade,44.517900,45.0,45.0,0.482100
3,3,grade:C,0.508389,8.406967e-21,grade,40.945034,41.0,41.0,0.054966
4,4,grade:D,0.438398,4.021486e-17,grade,35.308076,35.0,35.0,-0.308076
5,5,grade:E,0.305116,5.433811e-11,grade,24.573655,25.0,25.0,0.426345
6,6,grade:F,0.118659,1.407234e-02,grade,9.556686,10.0,10.0,0.443314
7,7,home_ownership:OWN,0.124618,4.754588e-10,home_ownership,10.036614,10.0,10.0,-0.036614
8,8,home_ownership:MORTGAGE,0.118705,1.926032e-21,home_ownership,9.560364,10.0,10.0,0.439636
9,9,addr_state:NM_VA,0.026225,4.103979e-01,addr_state,2.112165,2.0,2.0,-0.112165
10,10,addr_state:NY,0.044263,6.600749e-02,addr_state,3.564897,4.0,4.0,0.435103
11,11,addr_state:OK_TN_MO_LA_MD_NC,0.069443,2.552190e-03,addr_state,5.592860,6.0,6.0,0.407140
12,12,addr_state:CA,0.051014,1.542964e-02,addr_state,4.108579,4.0,4.0,-0.108579
13,13,addr_state:UT_KY_AZ_NJ,0.076670,1.963345e-03,addr_state,6.174883,6.0,6.0,-0.174883
14,14,addr_state:AR_MI_PA_OH_MN,0.145321,8.210777e-11,addr_state,11.703991,12.0,12.0,0.296009
15,15,addr_state:RI_MA_DE_SD_IN,0.107336,2.984297e-04,addr_state,8.644723,9.0,9.0,0.355277
16,16,addr_state:GA_WA_OR,0.181457,7.785881e-12,addr_state,14.614330,15.0,15.0,0.385670
17,17,addr_state:WI_MT,0.250245,1.221514e-07,addr_state,20.154431,20.0,20.0,-0.154431
18,18,addr_state:TX,0.221789,9.097757e-18,addr_state,17.862633,18.0,18.0,0.137367
19,19,addr_state:IL_CT,0.259020,4.774618e-19,addr_state,20.861194,21.0,21.0,0.138806
20,20,addr_state:KS_SC_CO_VT_AK_MS,0.328606,9.025887e-27,addr_state,26.465556,26.0,26.0,-0.465556
21,21,addr_state:WV_NH_WY_DC_ME_ID,0.511206,4.755606e-22,addr_state,41.171949,41.0,41.0,-0.171949
22,22,verification_status:Not Verified,0.108831,3.748874e-14,verification_status,8.765161,9.0,9.0,0.234839
23,23,verification_status:Source Verified,0.107015,2.794866e-16,verification_status,8.618855,9.0,9.0,0.381145
24,24,purpose:credit_card,0.403017,9.192724e-47,purpose,32.458510,32.0,32.0,-0.458510
25,25,purpose:debt_consolidation,0.307076,9.461949e-33,purpose,24.731531,25.0,25.0,0.268469
26,26,purpose:oth__med__vacation,0.302496,1.187529e-22,purpose,24.362639,24.0,24.0,-0.362639
27,27,purpose:major_purch__car__home_impr,0.358567,6.871187e-31,purpose,28.878599,29.0,29.0,0.121401
28,28,initial_list_status:w,0.290605,6.298864e-129,initial_list_status,23.405023,23.0,23.0,-0.405023
29,29,term:36,0.115606,5.903476e-17,term,9.310788,9.0,9.0,-0.310788
30,30,emp_length:1,0.060129,1.950262e-02,emp_length,4.842752,5.0,5.0,0.157248
31,31,emp_length:2-4,0.086859,3.352538e-06,emp_length,6.995496,7.0,7.0,0.004504
32,32,emp_length:5-6,0.030682,1.478691e-01,emp_length,2.471091,2.0,2.0,-0.471091
33,33,emp_length:7-9,0.041639,4.365611e-02,emp_length,3.353532,3.0,3.0,-0.353532
34,34,emp_length:10,0.118887,7.612872e-11,emp_length,9.575049,10.0,10.0,0.424951
35,35,int_rate:<9.548,1.419294,3.398607e-86,int_rate,114.308253,114.0,114.0,-0.308253
36,36,int_rate:9.548-12.025,0.790424,2.412814e-83,int_rate,63.659840,64.0,64.0,0.340160
37,37,int_rate:12.025-15.74,0.468757,1.205946e-43,int_rate,37.753113,38.0,38.0,0.246887
38,38,int_rate:15.74-20.281,0.135698,1.127108e-06,int_rate,10.928954,11.0,11.0,0.071046
39,39,inq_last_6mths:0,1.111689,5.813347e-54,inq_last_6mths,89.534132,90.0,90.0,0.465868
40,40,inq_last_6mths:1-2,0.940718,3.958648e-39,inq_last_6mths,75.764348,76.0,76.0,0.235652
41,41,inq_last_6mths:3-6,0.700868,8.494720e-22,inq_last_6mths,56.447115,56.0,56.0,-0.447115
42,42,pub_rec:3-4,0.458068,5.972584e-07,pub_rec,36.892238,37.0,37.0,0.107762
43,43,pub_rec:>=5,0.511154,7.233382e-03,pub_rec,41.167727,41.0,41.0,-0.167727
44,44,acc_now_delinq:>=1,0.161133,8.202582e-02,acc_now_delinq,12.977482,13.0,13.0,0.022518
45,45,total_rev_hi_lim:5K-10K,0.112690,3.014391e-06,total_rev_hi_lim,9.075913,9.0,9.0,-0.075913
46,46,total_rev_hi_lim:10K-20K,0.128752,1.733791e-08,total_rev_hi_lim,10.369528,10.0,10.0,-0.369528
47,47,total_rev_hi_lim:20K-30K,0.164783,2.326464e-11,total_rev_hi_lim,13.271421,13.0,13.0,-0.271421
48,48,total_rev_hi_lim:30K-40K,0.204428,1.020445e-13,total_rev_hi_lim,16.464416,16.0,16.0,-0.464416
49,49,total_rev_hi_lim:40K-55K,0.254772,1.298464e-17,total_rev_hi_lim,20.519066,21.0,21.0,0.480934
50,50,total_rev_hi_lim:55K-95K,0.305881,5.761258e-20,total_rev_hi_lim,24.635261,25.0,25.0,0.364739
51,51,total_rev_hi_lim:>95K,0.490732,2.268151e-19,total_rev_hi_lim,39.522961,40.0,40.0,0.477039
52,52,annual_inc:20K-30K,-0.074616,7.368734e-02,annual_inc,-6.009522,-6.0,-6.0,0.009522
53,53,annual_inc:30K-40K,-0.013788,7.309034e-01,annual_inc,-1.110433,-1.0,-1.0,0.110433
54,54,annual_inc:40K-50K,0.079486,4.696730e-02,annual_inc,6.401748,6.0,6.0,-0.401748
55,55,annual_inc:50K-60K,0.141284,4.913828e-04,annual_inc,11.378835,11.0,11.0,-0.378835
56,56,annual_inc:60K-70K,0.215361,2.122548e-07,annual_inc,17.344942,17.0,17.0,-0.344942
57,57,annual_inc:70K-80K,0.284304,2.009953e-11,annual_inc,22.897476,23.0,23.0,0.102524
58,58,annual_inc:80K-90K,0.359728,4.037315e-16,annual_inc,28.972067,29.0,29.0,0.027933
59,59,annual_inc:90K-100K,0.380010,1.105410e-16,annual_inc,30.605584,31.0,31.0,0.394416
60,60,annual_inc:100K-120K,0.454851,1.509406e-23,annual_inc,36.633174,37.0,37.0,0.366826
61,61,annual_inc:120K-140K,0.537967,2.635653e-25,annual_inc,43.327226,43.0,43.0,-0.327226
62,62,annual_inc:>140K,0.466320,1.439752e-22,annual_inc,37.556895,38.0,38.0,0.443105
63,63,dti:<=1.4,-0.205807,1.217936e-02,dti,-16.575441,-17.0,-17.0,-0.424559
64,64,dti:1.4-3.5,-0.038423,5.750912e-01,dti,-3.094572,-3.0,-3.0,0.094572
65,65,dti:3.5-7.7,-0.000915,9.875640e-01,dti,-0.073677,-0.0,-0.0,0.073677
66,66,dti:7.7-10.5,-0.064415,2.689273e-01,dti,-5.187879,-5.0,-5.0,0.187879
67,67,dti:10.5-16.1,-0.144861,9.922862e-03,dti,-11.666910,-12.0,-12.0,-0.333090
68,68,dti:16.1-20.3,-0.247354,1.098719e-05,dti,-19.921615,-20.0,-20.0,-0.078385
69,69,dti:20.3-21.7,-0.259843,1.056486e-05,dti,-20.927489,-21.0,-21.0,-0.072511
70,70,dti:21.7-22.4,-0.296897,2.582042e-06,dti,-23.911703,-24.0,-24.0,-0.088297
71,71,dti:22.4-35,-0.290472,1.799114e-07,dti,-23.394249,-23.0,-23.0,0.394249
72,0,grade:G,0.000000,NaN,grade,0.000000,0.0,0.0,0.000000
73,1,home_ownership:RENT_OTHER_NONE_ANY,0.000000,NaN,home_ownership,0.000000,0.0,0.0,0.000000
74,2,addr_state:ND_NE_IA_NV_FL_HI_AL,0.000000,NaN,addr_state,0.000000,0.0,0.0,0.000000
75,3,verification_status:Verified,0.000000,NaN,verification_status,0.000000,0.0,0.0,0.000000
76,4,purpose:educ__sm_b__wedd__ren_en__mov__house,0.000000,NaN,purpose,0.000000,0.0,0.0,0.000000
77,5,initial_list_status:f,0.000000,NaN,initial_list_status,0.000000,0.0,0.0,0.000000
78,6,term:60,0.000000,NaN,term,0.000000,0.0,0.0,0.000000
79,7,emp_length:0,0.000000,NaN,emp_length,0.000000,0.0,0.0,0.000000
80,8,int_rate:>20.281,0.000000,NaN,int_rate,0.000000,0.0,0.0,0.000000
81,9,inq_last_6mths:>6,0.000000,NaN,inq_last_6mths,0.000000,0.0,0.0,0.000000
82,10,pub_rec:0-2,0.000000,NaN,pub_rec,0.000000,0.0,0.0,0.000000
83,11,acc_now_delinq:0,0.000000,NaN,acc_now_delinq,0.000000,0.0,0.0,0.000000
84,12,total_rev_hi_lim:<=5K,0.000000,NaN,total_rev_hi_lim,0.000000,0.0,0.0,0.000000
85,13,annual_inc:<20K,0.000000,NaN,annual_inc,0.000000,0.0,0.0,0.000000
86,14,dti:>35,0.000000,NaN,dti,0.000000,0.0,0.0,0.000000

In [39]:
inputs_train_With_ref_cat_w_intercept = inputs_train_With_ref_categories
inputs_train_With_ref_cat_w_intercept.insert(0,'Intercept', 1)
inputs_train_With_ref_cat_w_intercept = inputs_train_With_ref_cat_w_intercept[df_scorecard['Feature name'].values]
inputs_train_With_ref_cat_w_intercept.head()

,Intercept,grade:A,grade:B,grade:C,grade:D,grade:E,grade:F,home_ownership:OWN,home_ownership:MORTGAGE,addr_state:NM_VA,...,initial_list_status:f,term:60,emp_length:0,int_rate:>20.281,inq_last_6mths:>6,pub_rec:0-2,acc_now_delinq:0,total_rev_hi_lim:<=5K,annual_inc:<20K,dti:>35
427211,1,1,0,0,0,0,0,0,1,0,...,1,0,0,0,0,1,1,0,0,0
206088,1,0,0,1,0,0,0,0,1,0,...,1,0,0,0,0,1,1,0,0,0
136020,1,1,0,0,0,0,0,0,1,0,...,1,0,0,0,0,1,1,0,0,0
412305,1,0,0,0,1,0,0,0,0,0,...,1,0,0,0,0,1,1,0,0,0
36159,1,0,0,1,0,0,0,0,1,0,...,1,0,0,0,0,1,1,0,0,0

In [40]:
inputs_2015_With_ref_cat_w_intercept = inputs_2015_With_ref_cat
inputs_2015_With_ref_cat_w_intercept.insert(0,'Intercept', 1)
inputs_2015_With_ref_cat_w_intercept = inputs_2015_With_ref_cat_w_intercept[df_scorecard['Feature name'].values]
inputs_2015_With_ref_cat_w_intercept.head()

,Intercept,grade:A,grade:B,grade:C,grade:D,grade:E,grade:F,home_ownership:OWN,home_ownership:MORTGAGE,addr_state:NM_VA,...,initial_list_status:f,term:60,emp_length:0,int_rate:>20.281,inq_last_6mths:>6,pub_rec:0-2,acc_now_delinq:0,total_rev_hi_lim:<=5K,annual_inc:<20K,dti:>35
id,,,,,,,,,,,,,,,,,,,,,
68444620,1,0,0,1,0,0,0,0,1,0,...,0,1,0,0,0,1,1,0,0,0
68547583,1,1,0,0,0,0,0,0,1,0,...,0,0,1,0,0,1,1,0,0,0
67849662,1,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,1,1,1,0,0
68506885,1,0,0,1,0,0,0,0,0,0,...,0,1,0,0,0,1,1,0,0,0
68341763,1,0,1,0,0,0,0,0,1,0,...,0,1,0,0,0,1,1,0,0,0

In [41]:
scorecard_scores = df_scorecard['Score - Final']
scorecard_scores = scorecard_scores.values.reshape(87,1)

In [42]:
y_scores_train = inputs_train_With_ref_cat_w_intercept.dot(scorecard_scores)
y_scores_train.head()

            0
427211  665.0
206088  592.0
136020  657.0
412305  491.0
36159   527.0

In [43]:
y_scores_2015 = inputs_2015_With_ref_cat_w_intercept.dot(scorecard_scores)
y_scores_2015.head()

              0
id
68444620  711.0
68547583  705.0
67849662  580.0
68506885  580.0
68341763  646.0

In [44]:
inputs_train_with_ref_cat_w_intercept = pd.concat([inputs_train_With_ref_cat_w_intercept, y_scores_train], axis = 1)
inputs_2015_with_ref_cat_w_intercept = pd.concat([inputs_2015_With_ref_cat_w_intercept, y_scores_2015], axis = 1)

In [45]:
inputs_train_with_ref_cat_w_intercept.columns.values[inputs_train_with_ref_cat_w_intercept.shape[1]-1] = 'Score'
inputs_2015_with_ref_cat_w_intercept.columns.values[inputs_2015_with_ref_cat_w_intercept.shape[1]-1] = 'Score'

In [46]:
# Creating dummy variables for score intervals with old (\"expected\")."
inputs_train_with_ref_cat_w_intercept['Score:300-350'] = np.where((inputs_train_with_ref_cat_w_intercept['Score'] >= 300) & (inputs_train_with_ref_cat_w_intercept['Score'] < 350), 1, 0)
inputs_train_with_ref_cat_w_intercept['Score:350-400'] = np.where((inputs_train_with_ref_cat_w_intercept['Score'] >= 350) & (inputs_train_with_ref_cat_w_intercept['Score'] < 400), 1, 0)
inputs_train_with_ref_cat_w_intercept['Score:400-450'] = np.where((inputs_train_with_ref_cat_w_intercept['Score'] >= 400) & (inputs_train_with_ref_cat_w_intercept['Score'] < 450), 1, 0)
inputs_train_with_ref_cat_w_intercept['Score:450-500'] = np.where((inputs_train_with_ref_cat_w_intercept['Score'] >= 450) & (inputs_train_with_ref_cat_w_intercept['Score'] < 500), 1, 0)
inputs_train_with_ref_cat_w_intercept['Score:500-550'] = np.where((inputs_train_with_ref_cat_w_intercept['Score'] >= 500) & (inputs_train_with_ref_cat_w_intercept['Score'] < 550), 1, 0)
inputs_train_with_ref_cat_w_intercept['Score:550-600'] = np.where((inputs_train_with_ref_cat_w_intercept['Score'] >= 550) & (inputs_train_with_ref_cat_w_intercept['Score'] < 600), 1, 0)
inputs_train_with_ref_cat_w_intercept['Score:600-650'] = np.where((inputs_train_with_ref_cat_w_intercept['Score'] >= 600) & (inputs_train_with_ref_cat_w_intercept['Score'] < 650), 1, 0)
inputs_train_with_ref_cat_w_intercept['Score:650-700'] = np.where((inputs_train_with_ref_cat_w_intercept['Score'] >= 650) & (inputs_train_with_ref_cat_w_intercept['Score'] < 700), 1, 0)
inputs_train_with_ref_cat_w_intercept['Score:700-750'] = np.where((inputs_train_with_ref_cat_w_intercept['Score'] >= 700) & (inputs_train_with_ref_cat_w_intercept['Score'] < 750), 1, 0)
inputs_train_with_ref_cat_w_intercept['Score:750-800'] = np.where((inputs_train_with_ref_cat_w_intercept['Score'] >= 750) & (inputs_train_with_ref_cat_w_intercept['Score'] < 800), 1, 0)
inputs_train_with_ref_cat_w_intercept['Score:800-850'] = np.where((inputs_train_with_ref_cat_w_intercept['Score'] >= 800) & (inputs_train_with_ref_cat_w_intercept['Score'] <= 850), 1, 0)

In [47]:
# Creating dummy variables for score intervals with new (\"actual\").
inputs_2015_with_ref_cat_w_intercept['Score:300-350'] = np.where((inputs_2015_with_ref_cat_w_intercept['Score'] >= 300) & (inputs_2015_with_ref_cat_w_intercept['Score'] < 350), 1, 0)
inputs_2015_with_ref_cat_w_intercept['Score:350-400'] = np.where((inputs_2015_with_ref_cat_w_intercept['Score'] >= 350) & (inputs_2015_with_ref_cat_w_intercept['Score'] < 400), 1, 0)
inputs_2015_with_ref_cat_w_intercept['Score:400-450'] = np.where((inputs_2015_with_ref_cat_w_intercept['Score'] >= 400) & (inputs_2015_with_ref_cat_w_intercept['Score'] < 450), 1, 0)
inputs_2015_with_ref_cat_w_intercept['Score:450-500'] = np.where((inputs_2015_with_ref_cat_w_intercept['Score'] >= 450) & (inputs_2015_with_ref_cat_w_intercept['Score'] < 500), 1, 0)
inputs_2015_with_ref_cat_w_intercept['Score:500-550'] = np.where((inputs_2015_with_ref_cat_w_intercept['Score'] >= 500) & (inputs_2015_with_ref_cat_w_intercept['Score'] < 550), 1, 0)
inputs_2015_with_ref_cat_w_intercept['Score:550-600'] = np.where((inputs_2015_with_ref_cat_w_intercept['Score'] >= 550) & (inputs_2015_with_ref_cat_w_intercept['Score'] < 600), 1, 0)
inputs_2015_with_ref_cat_w_intercept['Score:600-650'] = np.where((inputs_2015_with_ref_cat_w_intercept['Score'] >= 600) & (inputs_2015_with_ref_cat_w_intercept['Score'] < 650), 1, 0)
inputs_2015_with_ref_cat_w_intercept['Score:650-700'] = np.where((inputs_2015_with_ref_cat_w_intercept['Score'] >= 650) & (inputs_2015_with_ref_cat_w_intercept['Score'] < 700), 1, 0)
inputs_2015_with_ref_cat_w_intercept['Score:700-750'] = np.where((inputs_2015_with_ref_cat_w_intercept['Score'] >= 700) & (inputs_2015_with_ref_cat_w_intercept['Score'] < 750), 1, 0)
inputs_2015_with_ref_cat_w_intercept['Score:750-800'] = np.where((inputs_2015_with_ref_cat_w_intercept['Score'] >= 750) & (inputs_2015_with_ref_cat_w_intercept['Score'] < 800), 1, 0)
inputs_2015_with_ref_cat_w_intercept['Score:800-850'] = np.where((inputs_2015_with_ref_cat_w_intercept['Score'] >= 800) & (inputs_2015_with_ref_cat_w_intercept['Score'] <= 850), 1, 0)

# 4 Population Stability Index

It is calculated with the following formula:  
PSI = sum( [Proportions actual new data_j - Proportions expected old data_j ] x ln (Proportions new data_j / Proportions old data_j) )

In [48]:
# Creating a df with proportions for the old (\"expected\") data.
PSI_calc_train = inputs_train_with_ref_cat_w_intercept.sum() / inputs_train_with_ref_cat_w_intercept.shape[0]
# Creating a df with proportions for the new (\"actual\") data.
PSI_calc_2015 = inputs_2015_with_ref_cat_w_intercept.sum() / inputs_2015_with_ref_cat_w_intercept.shape[0]

In [49]:
# Concating two dfs along the columns.
PSI_calc = pd.concat([PSI_calc_train, PSI_calc_2015], axis = 1)

In [50]:
# Resetting the index.
PSI_calc = PSI_calc.reset_index()
# Creating a new column
PSI_calc['Original feature name'] = PSI_calc['index'].str.split(':').str[0]
# Changing col names of df
PSI_calc.columns = ['index', 'Prop_Train', 'Prop_New', 'Orig feature']
# Keeping neccessary cols
PSI_calc = PSI_calc[np.array(['index', 'Orig feature', 'Prop_Train', 'Prop_New'])]
# Removing some rows
PSI_calc = PSI_calc[(PSI_calc['index'] != 'Intercept') & (PSI_calc['index'] != 'Score')]

In [51]:
# Calculating contribution of each dummy var to PSI
# If props are 0, the contribution is 0,
# Otherwise, PSI formula is applied
PSI_calc['Contribution'] = np.where((PSI_calc['Prop_Train'] == 0) |\
                                    (PSI_calc['Prop_New'] == 0), 0,\
                                    (PSI_calc['Prop_New'] - PSI_calc['Prop_Train']) * np.log(PSI_calc['Prop_New'] / PSI_calc['Prop_Train']))

C:\Users\Admin\anaconda3\lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

In [52]:
PSI_calc

,index,Orig feature,Prop_Train,Prop_New,Contribution
1,grade:A,grade,0.160200,0.174154,1.165355e-03
2,grade:B,grade,0.294160,0.279287,7.717123e-04
3,grade:C,grade,0.268733,0.286318,1.114660e-03
4,grade:D,grade,0.164862,0.148789,1.648763e-03
5,grade:E,grade,0.076702,0.082993,4.959607e-04
6,grade:F,grade,0.028228,0.023313,9.403837e-04
7,home_ownership:OWN,home_ownership,0.089256,0.108684,3.825896e-03
8,home_ownership:MORTGAGE,home_ownership,0.506546,0.493196,3.565650e-04
9,addr_state:NM_VA,addr_state,0.036032,0.034159,1.000374e-04
10,addr_state:NY,addr_state,0.086350,0.080372,4.289495e-04
11,addr_state:OK_TN_MO_LA_MD_NC,addr_state,0.100475,0.106302,3.284590e-04
12,addr_state:CA,addr_state,0.153337,0.137896,1.638977e-03
13,addr_state:UT_KY_AZ_NJ,addr_state,0.078742,0.075620,1.263345e-04
14,addr_state:AR_MI_PA_OH_MN,addr_state,0.117155,0.122894,2.745053e-04
15,addr_state:RI_MA_DE_SD_IN,addr_state,0.047128,0.049162,8.599362e-05
16,addr_state:GA_WA_OR,addr_state,0.067410,0.066425,1.452530e-05
17,addr_state:WI_MT,addr_state,0.015664,0.016208,1.857778e-05
18,addr_state:TX,addr_state,0.078166,0.082402,2.235882e-04
19,addr_state:IL_CT,addr_state,0.055245,0.055073,5.361432e-07
20,addr_state:KS_SC_CO_VT_AK_MS,addr_state,0.049168,0.052955,2.809986e-04
21,addr_state:WV_NH_WY_DC_ME_ID,addr_state,0.015591,0.015348,3.823618e-06
22,verification_status:Not Verified,verification_status,0.317896,0.281441,4.440272e-03
23,verification_status:Source Verified,verification_status,0.321772,0.426425,2.946951e-02
24,purpose:credit_card,purpose,0.224061,0.242286,1.425150e-03
25,purpose:debt_consolidation,purpose,0.587578,0.593739,6.427034e-05
26,purpose:oth__med__vacation,purpose,0.065837,0.060298,4.868175e-04
27,purpose:major_purch__car__home_impr,purpose,0.089538,0.085983,1.439721e-04
28,initial_list_status:w,initial_list_status,0.349877,0.634659,1.695889e-01
29,term:36,term,0.724929,0.672467,3.940988e-03
30,emp_length:1,emp_length,0.063411,0.065242,5.213149e-05
31,emp_length:2-4,emp_length,0.227197,0.226631,1.413359e-06
32,emp_length:5-6,emp_length,0.121945,0.099189,4.700088e-03
33,emp_length:7-9,emp_length,0.142534,0.134751,4.369352e-04
34,emp_length:10,emp_length,0.322348,0.336077,5.725772e-04
35,int_rate:<9.548,int_rate,0.179909,0.279330,4.373944e-02
36,int_rate:9.548-12.025,int_rate,0.168111,0.180914,9.398183e-04
37,int_rate:12.025-15.74,int_rate,0.348877,0.319238,2.631566e-03
38,int_rate:15.74-20.281,int_rate,0.224182,0.176659,1.132159e-02
39,inq_last_6mths:0,inq_last_6mths,0.518009,0.608907,1.469556e-02
40,inq_last_6mths:1-2,inq_last_6mths,0.403125,0.350606,7.330911e-03
41,inq_last_6mths:3-6,inq_last_6mths,0.077860,0.040487,2.443887e-02
42,pub_rec:3-4,pub_rec,0.004525,0.009309,3.450881e-03
43,pub_rec:>=5,pub_rec,0.001161,0.002494,1.019015e-03
44,acc_now_delinq:>=1,acc_now_delinq,0.003608,0.005657,9.209557e-04
45,total_rev_hi_lim:5K-10K,total_rev_hi_lim,0.146292,0.102949,1.522983e-02
46,total_rev_hi_lim:10K-20K,total_rev_hi_lim,0.292434,0.263257,3.066676e-03
47,total_rev_hi_lim:20K-30K,total_rev_hi_lim,0.192573,0.202121,4.620848e-04
48,total_rev_hi_lim:30K-40K,total_rev_hi_lim,0.116300,0.132289,2.059687e-03
49,total_rev_hi_lim:40K-55K,total_rev_hi_lim,0.094097,0.117907,5.370656e-03
50,total_rev_hi_lim:55K-95K,total_rev_hi_lim,0.073941,0.107235,1.237733e-02
51,total_rev_hi_lim:>95K,total_rev_hi_lim,0.023966,0.041459,9.587017e-03
52,annual_inc:20K-30K,annual_inc,0.059848,0.055011,4.075655e-04
53,annual_inc:30K-40K,annual_inc,0.115627,0.107577,5.808781e-04
54,annual_inc:40K-50K,annual_inc,0.147560,0.139959,4.019516e-04
55,annual_inc:50K-60K,annual_inc,0.142917,0.137352,2.210361e-04
56,annual_inc:60K-70K,annual_inc,0.116257,0.114457,2.808921e-05
57,annual_inc:70K-80K,annual_inc,0.100218,0.101963,3.013307e-05
58,annual_inc:80K-90K,annual_inc,0.075321,0.075926,4.833976e-06
59,annual_inc:90K-100K,annual_inc,0.060553,0.063228,1.156411e-04
60,annual_inc:100K-120K,annual_inc,0.070831,0.076921,5.023030e-04
61,annual_inc:120K-140K,annual_inc,0.036791,0.041756,6.284529e-04
62,annual_inc:>140K,annual_inc,0.058886,0.071556,2.469405e-03
63,dti:<=1.4,dti,0.008123,0.004329,2.387190e-03
64,dti:1.4-3.5,dti,0.020682,0.015695,1.376168e-03
65,dti:3.5-7.7,dti,0.089865,0.073155,3.437682e-03
66,dti:7.7-10.5,dti,0.096274,0.081186,2.571869e-03
67,dti:10.5-16.1,dti,0.249282,0.219854,3.696793e-03
68,dti:16.1-20.3,dti,0.188844,0.175875,9.226461e-04
69,dti:20.3-21.7,dti,0.056626,0.054233,1.033470e-04
70,dti:21.7-22.4,dti,0.026263,0.025764,9.595279e-06
71,dti:22.4-35,dti,0.256316,0.309722,1.010782e-02
72,grade:G,grade,0.007115,0.005146,6.376914e-04
73,home_ownership:RENT_OTHER_NONE_ANY,home_ownership,0.404198,0.398120,9.207217e-05
74,addr_state:ND_NE_IA_NV_FL_HI_AL,addr_state,0.099537,0.105186,3.118056e-04
75,verification_status:Verified,verification_status,0.360332,0.292134,1.430879e-02
76,purpose:educ__sm_b__wedd__ren_en__mov__house,purpose,0.032987,0.017694,9.525033e-03
77,initial_list_status:f,initial_list_status,0.650123,0.365341,1.641280e-01
78,term:60,term,0.275071,0.327533,9.157781e-03
79,emp_length:0,emp_length,0.122565,0.138109,1.856168e-03
80,int_rate:>20.281,int_rate,0.078922,0.043860,2.059771e-02
81,inq_last_6mths:>6,inq_last_6mths,0.001005,0.000000,0.000000e+00
82,pub_rec:0-2,pub_rec,0.994314,0.988197,3.774406e-05
83,acc_now_delinq:0,acc_now_delinq,0.996392,0.994343,4.215415e-06
84,total_rev_hi_lim:<=5K,total_rev_hi_lim,0.060398,0.032784,1.687267e-02
85,annual_inc:<20K,annual_inc,0.015192,0.014294,5.473559e-05
86,dti:>35,dti,0.007726,0.040188,5.352976e-02
88,Score:300-350,Score,0.000003,0.000000,0.000000e+00
89,Score:350-400,Score,0.000105,0.000017,1.616839e-04
90,Score:400-450,Score,0.004131,0.002073,1.418817e-03
91,Score:450-500,Score,0.065537,0.040210,1.237240e-02
92,Score:500-550,Score,0.246258,0.169938,2.831012e-02
93,Score:550-600,Score,0.340159,0.292236,7.277179e-03
94,Score:600-650,Score,0.214732,0.235959,2.001073e-03
95,Score:650-700,Score,0.110552,0.201594,5.469519e-02
96,Score:700-750,Score,0.018379,0.057322,4.429590e-02
97,Score:750-800,Score,0.000145,0.000651,7.603754e-04
98,Score:800-850,Score,0.000000,0.000000,0.000000e+00

In [53]:
# Summing all contributions by original feature name
PSI_calc.groupby('Orig feature')['Contribution'].sum()

Orig feature
Score                  0.151293
acc_now_delinq         0.000925
addr_state             0.003837
annual_inc             0.005445
dti                    0.078143
emp_length             0.007619
grade                  0.006775
home_ownership         0.004275
initial_list_status    0.333717
inq_last_6mths         0.046465
int_rate               0.079230
pub_rec                0.004508
purpose                0.011645
term                   0.013099
total_rev_hi_lim       0.065026
verification_status    0.048219
Name: Contribution, dtype: float64

Population Stability Index is less than 0.25 for most of the categories. 

However, it is very high for the initial list status: 0.33. It could be due to the change of the population in the new data and the banks' policy about its definition.